#!/usr/bin/env python3
"""Build roster_related.json for physics-adjacent departments (coarse, roster-level).

Data captured from official UCAS college faculty pages:
- 天文与空间科学学院 (astro.ucas.ac.cn)  专任教师
- 材料科学与光电技术学院 (cmo.ucas.ac.cn) 专任教师
- 化学科学学院 (chem.ucas.ac.cn) 专任教师  (subset: physics-adjacent physical chemistry)
- 数学科学学院 (math.ucas.ac.cn) 专任教师  (subset: mathematical physics / relevant)
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

ASTRO = [
 ("安军社","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~anjunshe"),
 ("白伟华","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~bwh"),
 ("白先勇","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~xianyongbai"),
 ("崔向群","https://people.ucas.ac.cn/~0000356"),
 ("常宏","https://people.ucas.ac.cn/~0009586"),
 ("蔡明辉","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~cmh"),
 ("陈俊平","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~junpingchen"),
 ("陈大明","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~DamingChen"),
 ("陈学雷","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~xuelei"),
 ("陈玉琴","https://people.ucas.ac.cn/~0000048"),
 ("杜翠花","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~dch"),
 ("董瑞芳","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~dongruifang"),
 ("董绍武","https://people.ucas.ac.cn/~0002835"),
 ("邓元勇","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~dengyuanyong"),
 ("邓劲松","https://people.ucas.ac.cn/~0007976"),
 ("范舟","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~zfan"),
 ("苟利军","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~lgou"),
 ("郭建恒","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~guojh"),
 ("高东","https://people.ucas.ac.cn/~0034237"),
 ("高玉平","https://people.ucas.ac.cn/~0005120"),
 ("侯俊峰","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~jfhou"),
 ("侯永辉","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~yhhou"),
 ("侯金良","https://people.ucas.ac.cn/~0000003"),
 ("洪晓瑜","https://people.ucas.ac.cn/~0004503"),
 ("韩占文","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhanwenhan"),
 ("韩建伟","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~hanjw"),
 ("韩文标","https://people.ucas.ac.cn/~0040680"),
 ("韩金林","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~jlhan"),
 ("黄乘利","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~clhuang"),
 ("黄勇","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~huangyong021"),
 ("黄样","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~yanghuang"),
 ("黄茂海","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~mh"),
 ("姜晓军","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~jiangxiaojun"),
 ("姜爱民","https://people.ucas.ac.cn/~0000050"),
 ("金驰川","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~cjin"),
 ("凌志兴","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~lingzhixing"),
 ("刘建军","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~Liujianjun"),
 ("刘涛","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~taoliu-ntsc"),
 ("刘碧芳","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~bfliu"),
 ("刘继峰","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~liujifeng"),
 ("刘超","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~liuchao"),
 ("刘静","https://people.ucas.ac.cn/~0000647"),
 ("卢晓春","https://people.ucas.ac.cn/~0005122"),
 ("廖石龙","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~liao.shilong"),
 ("李婷","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~liting"),
 ("李宏伟","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~lhw"),
 ("李常伟","https://people.ucas.ac.cn/~0036347"),
 ("李建斌","https://people.ucas.ac.cn/~0046915"),
 ("李春来","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~lichunlai"),
 ("李晖","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~hli_nssc"),
 ("李焱","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~ly0at0ynao"),
 ("李磊","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~lil"),
 ("李进","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~lijin"),
 ("林隽","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~jlin"),
 ("罗冰显","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~luobx"),
 ("陆由俊","https://people.ucas.ac.cn/~0012269"),
 ("黎耕","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~ligeng"),
 ("马英起","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~mayingqi"),
 ("马骏","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~majun"),
 ("欧阳自远","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~ouyangziyuan"),
 ("平劲松","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~pjs"),
 ("乔二林","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~qiaoel"),
 ("齐朝祥","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~qzx"),
 ("任鑫","https://people.ucas.ac.cn/~0029580"),
 ("孙保琪","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~sunbaoqi"),
 ("孙宁晨","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~sunnc"),
 ("孙越强","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~sunyueqiang"),
 ("师立勤","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~shiliqin"),
 ("施建荣","https://people.ucas.ac.cn/~0008043"),
 ("苏彦","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~suyan"),
 ("苏江涛","https://people.ucas.ac.cn/~0030251"),
 ("唐正宏","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~tangzhenghong"),
 ("汤勇","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~yongtang"),
 ("田文武","https://people.ucas.ac.cn/~0017282"),
 ("谭宝林","https://people.ucas.ac.cn/~0019070"),
 ("吴京文","https://people.ucas.ac.cn/~0052338"),
 ("吴宏","https://people.ucas.ac.cn/~0005926"),
 ("武向平","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~wxp"),
 ("武振宇","https://people.ucas.ac.cn/~0007983"),
 ("王咏梅","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~0002956"),
 ("王国民","https://people.ucas.ac.cn/~0005697"),
 ("王小亚","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~XiaoyaWang"),
 ("王岚","https://people.ucas.ac.cn/~0024576"),
 ("王广利","https://people.ucas.ac.cn/~0004515"),
 ("王建民","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~wangjm"),
 ("王杰","https://people.ucas.ac.cn/~0024581"),
 ("王汇娟","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~huijuanwang"),
 ("王菲鹿","https://people.ucas.ac.cn/~0024031"),
 ("王鑫","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~wxn"),
 ("王靓","https://people.ucas.ac.cn/~0067772"),
 ("魏建彦","https://people.ucas.ac.cn/~0000040"),
 ("于京龙","https://people.ucas.ac.cn/~0046917"),
 ("于涌","https://people.ucas.ac.cn/~0040681"),
 ("杨书红","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~shuhongyang"),
 ("杨尚斌","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~yangshangbin"),
 ("杨旭海","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~yyang123"),
 ("袁为民","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~wmy"),
 ("闫昌硕","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~yancs"),
 ("颜毅华","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~0000042"),
 ("左维","https://people.ucas.ac.cn/~0008006"),
 ("张冕","https://people.ucas.ac.cn/~0046926"),
 ("张天萌","https://people.ucas.ac.cn/~0026673"),
 ("张振龙","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~zzl"),
 ("张枚","https://people.ucas.ac.cn/~0005855"),
 ("张洪波","https://people.ucas.ac.cn/~0007990"),
 ("张爱兵","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhab2025"),
 ("张珅毅","https://people.ucas.ac.cn/~0017768"),
 ("张臣","https://people.ucas.ac.cn/~0017361"),
 ("张首刚","https://people.ucas.ac.cn/~0000030"),
 ("朱永田","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~ytzhu"),
 ("章海鹰","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~seagle"),
 ("赵公博","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~gongbo"),
 ("赵刚","https://people.ucas.ac.cn/~0005514"),
 ("赵永恒","https://people.ucas.ac.cn/~0005834"),
 ("邹德财","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~ntsczdc"),
 ("郑建华","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~Jianhua"),
 ("钟秋珍","https://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhongqiuzhen"),
]

CMO = [
 ("安俊明","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~anjunming1010"),
 ("白海洋","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~hybai"),
 ("成步文","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~Buwen Cheng"),
 ("蔡芸皓","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~caiyunhao"),
 ("陈博","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~cb0067"),
 ("陈嘉民","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~jiaminchen"),
 ("陈少武","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~swchen2012"),
 ("陈平","http://people.ucas.ac.cn/~0024532"),
 ("陈广超","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~chen"),
 ("陈弘","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~_chenhong"),
 ("陈春英","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~chunyingchen"),
 ("陈涌海","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~yhchen"),
 ("陈立泉","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~chenliquan"),
 ("陈运法","http://people.ucas.ac.cn/~0003801"),
 ("董登峰","http://people.ucas.ac.cn/~0046890"),
 ("邓惠雄","http://people.ucas.ac.cn/~0040942"),
 ("封红青","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~hqfeng"),
 ("谷战军","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zjgu"),
 ("郭喜庆","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~guoxiqing"),
 ("洪茂椿","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~hmc"),
 ("胡勇胜","http://people.ucas.ac.cn/~0010427"),
 ("韩伟华","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~whhan"),
 ("韩秀峰","http://people.ucas.ac.cn/~0000799"),
 ("黄北举","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~bjhuang"),
 ("黄学杰","http://people.ucas.ac.cn/~0002772"),
 ("黄永箴","http://people.ucas.ac.cn/~0000992"),
 ("黄继军","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~jjhuang"),
 ("黄辉","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~huanghui"),
 ("姜宇航","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~yuhangjiang"),
 ("季海铭","http://people.ucas.ac.cn/~0042818"),
 ("金鹏","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~pengjin"),
 ("阚强","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~kanqiang"),
 ("刘丰珍","http://people.ucas.ac.cn/~0002005"),
 ("刘仁材","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~jtliu"),
 ("刘俊岐","http://people.ucas.ac.cn/~0029365"),
 ("刘剑","http://people.ucas.ac.cn/~0005302"),
 ("刘向峰","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~xiangfengliu"),
 ("刘媛媛","http://people.ucas.ac.cn/~0010841"),
 ("刘孔","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~liukong"),
 ("刘安金","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~AnjinLiu"),
 ("刘峰奇","http://people.ucas.ac.cn/~0000999"),
 ("刘志强","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~liuzhiqiang01"),
 ("刘育梁","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~liuyuliang"),
 ("刘舒曼","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~Liushuman"),
 ("李一叶","http://people.ucas.ac.cn/~0039563"),
 ("李冬梅","http://people.ucas.ac.cn/~0036228"),
 ("李剑峰","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~jfli"),
 ("李如康","http://people.ucas.ac.cn/~0004984"),
 ("李彦超","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~ycli"),
 ("李晓毅","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~lixiaoyi"),
 ("李树深","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~sslee"),
 ("李泓","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~lihong"),
 ("李芳","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~iscaslf"),
 ("林哲帅","http://people.ucas.ac.cn/~0010910"),
 ("林学春","http://people.ucas.ac.cn/~0008355"),
 ("梁松","http://people.ucas.ac.cn/~0029496"),
 ("罗先刚","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~luoxiangang"),
 ("陆丹","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~ludan"),
 ("骆军委","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~jwluo"),
 ("孟庆波","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~qbmeng"),
 ("苗兵","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~bmiao"),
 ("马文全","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~wqma"),
 ("马骁宇","http://people.ucas.ac.cn/~0000993"),
 ("马骥","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~ma_ji"),
 ("倪海桥","http://people.ucas.ac.cn/~0022423"),
 ("彭爱东","http://people.ucas.ac.cn/~0024163"),
 ("潘教青","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~panjiaoqing"),
 ("蒲明博","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~pmb"),
 ("屈小中","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~quxz"),
 ("曲胜春","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~qushengchun"),
 ("祁志美","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zmqi"),
 ("祁楠","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~qinan"),
 ("齐月静","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~imeqiyuejing"),
 ("史钦钦","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~SHIQINQIN"),
 ("孙辉","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~sunhui"),
 ("宋国峰","http://people.ucas.ac.cn/~0003053"),
 ("施兴华","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~shixh"),
 ("施剑林","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~jlshi"),
 ("申超","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~0041661"),
 ("苏娟娟","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~juanjuan"),
 ("谭平恒","http://people.ucas.ac.cn/~0001010"),
 ("谭满清","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~mqtan.ucas.edu.cn"),
 ("吴远大","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~wuyuanda"),
 ("汪卫华","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~_whwang"),
 ("王军喜","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~junxiwang"),
 ("王利军","http://people.ucas.ac.cn/~0008365"),
 ("王占国","http://people.ucas.ac.cn/~0003783"),
 ("王启明","http://people.ucas.ac.cn/~0000989"),
 ("王国伟","http://people.ucas.ac.cn/~0046865"),
 ("王国宏","http://people.ucas.ac.cn/~0002563"),
 ("王大志","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~wangdazhi"),
 ("王开友","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~kywang"),
 ("王强斌","http://people.ucas.ac.cn/~0009897"),
 ("王晓东","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~wangxiaodong"),
 ("王智杰","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~wangzhijie"),
 ("王海龙","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~hlwang"),
 ("韦欣","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~weixin"),
 ("魏大海","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~dhwei"),
 ("魏钟鸣","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~Zhongming Wei"),
 ("向军辉","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~xiangjh"),
 ("徐云","http://people.ucas.ac.cn/~0021034"),
 ("徐团伟","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~xutuanwei"),
 ("徐应强","http://people.ucas.ac.cn/~0022422"),
 ("徐波","http://people.ucas.ac.cn/~0008369"),
 ("肖小玲","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~xiao"),
 ("肖金龙","http://people.ucas.ac.cn/~0026433"),
 ("薛春来","http://people.ucas.ac.cn/~0029503"),
 ("许兴胜","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~0004546"),
 ("谢亮","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~0002596"),
 ("于海娟","http://people.ucas.ac.cn/~0021031"),
 ("伊晓燕","http://people.ucas.ac.cn/~0021780"),
 ("叶小玲","http://people.ucas.ac.cn/~0042810"),
 ("尹志岗","http://people.ucas.ac.cn/~0021005"),
 ("杨军","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~junyangipe"),
 ("杨华","http://people.ucas.ac.cn/~0024534"),
 ("杨富华","http://people.ucas.ac.cn/~0005935"),
 ("杨少延","http://people.ucas.ac.cn/~0008371"),
 ("杨晓光","http://people.ucas.ac.cn/~0042817"),
 ("杨晓红","http://people.ucas.ac.cn/~0010842"),
 ("杨林","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~yanglin"),
 ("杨跃德","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~yyd"),
 ("杨身园","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~syyang"),
 ("游经碧","http://people.ucas.ac.cn/~0040956"),
 ("袁国栋","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~guodongyuan"),
 ("袁方利","http://people.ucas.ac.cn/~0000276"),
 ("闫建昌","http://people.ucas.ac.cn/~0024533"),
 ("闫清波","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~yan"),
 ("周玉琴","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhouyuqin"),
 ("周玉荣","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhouyr"),
 ("周维虎","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhouweihu"),
 ("左玉华","http://people.ucas.ac.cn/~0001867"),
 ("张伟刚","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~WGZHANG"),
 ("张俊","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhangjwill"),
 ("张兴旺","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~xwzhang"),
 ("张冶金","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhangyejin"),
 ("张天然","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~tianranzhang"),
 ("张文涛","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhangwtsemi"),
 ("张新惠","http://people.ucas.ac.cn/~0003918"),
 ("张明亮","http://people.ucas.ac.cn/~0029370"),
 ("张滋黎","http://people.ucas.ac.cn/~0024026"),
 ("张继成","http://people.ucas.ac.cn/~0040611"),
 ("张静","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhangj271"),
 ("张韵","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhangyun34"),
 ("赵军","http://people.ucas.ac.cn/~0015378"),
 ("赵宇亮","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhaoyuliang"),
 ("赵有文","http://people.ucas.ac.cn/~0001012"),
 ("赵玲娟","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~zhaolingjuan"),
 ("赵颖","http://people.ucas.ac.cn/~0017584"),
 ("郑军","http://people.ucas.ac.cn/~0034810"),
 ("郑厚植","http://people.ucas.ac.cn/~0004960"),
 ("郑晓鹏","http://people.ucas.ac.cn/http://people.ucas.ac.cn/~xiaopengzheng"),
]

profs = []
for name, url in ASTRO:
    profs.append({
        "name": name, "name_local": name,
        "school": "中国科学院大学", "department": "天文与空间科学学院",
        "title": "", "subject": "Astronomy & Space Science",
        "research_directions": [], "focus_areas": [], "publications": [],
        "profile_url": url,
    })
for name, url in CMO:
    profs.append({
        "name": name, "name_local": name,
        "school": "中国科学院大学", "department": "材料科学与光电技术学院",
        "title": "", "subject": "Materials Science & Optoelectronics",
        "research_directions": [], "focus_areas": [], "publications": [],
        "profile_url": url,
    })

out = {"professors": profs}
(HERE / "data" / "roster_related.json").write_text(
    json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Wrote roster_related.json: {len(profs)} professors")
